[tool.ruff]
line-length = 130
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "CPY001", # missing-copyright-notice
  "D100",  # missing module docstring
  "D101",  # missing class docstring
  "D102",  # missing method docstring
  "D103",  # missing function docstring
  "D104",  # missing package docstring
  "D105",  # missing magic method docstring
  "D106",  # missing nested class docstring
  "D107",  # missing __init__ docstring
  "D203",  # blank line required before class docstring
  "D211",  # no-blank-line-before-class
  "D213",  # multi-line-summary-second-line
  "DOC201", # `return` is not documented in docstringRuff
  "DOC501", # docstring-missing-exception
  "FBT001", # boolean-type-hint-positional-argument
  "FBT003", # boolean-positional-value-in-call
  "PLR0913", # Too many arguments in function definition
  "PLR0917", # too-many-positional-arguments
  "S101",  # use of assert detected (allowed in tests)
  "UP045", # non-pep604-annotation-optional
  "PLR6301", # Method could be a function, class method, or static methodRuff
  "FBT002", # boolean-default-value-positional-argument
]
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
